### ISSUE TITLE
How do we modify the generated link?

### ISSUE THREAD

**Issue by wooilok123** [j-dogcoder/Blackeye-2.0#22]
Dear Developer, im really appreciate your effort on developing this project! It works pretty well, may i ask how do users like us , modify the generated link? because it may seem suspicious with the generated link. Hope to get your reply soon ! have a great day ahead

**Comment by j-dogcoder** [comment]
I do not think you can modify the link at the current time. That would be something to work on. I will mark this as open and see if someone can get to it. I am not sure this is possible due to the way Ngrok works, but I will look into it.
