### ISSUE TITLE
Website link not creating 

### ISSUE THREAD

**Issue by bobv1st** [j-dogcoder/Blackeye-2.0#24]
When creating the phishing site it does not give a link to send instead it is empty

![Capture](https://user-images.githubusercontent.com/74991190/100283859-2478d380-2f66-11eb-9057-77af9934129b.JPG)

**Comment by j-dogcoder** [comment]
I think there is a fix for this.

1. you have to navigate to the directory blackeye
`cd blackeye`
2. run blackeye.sh
`bash blackeye.sh`
3.stop the prosses (using control+c)
4. now do
`sudo ./ngrok authtoken replacewithyourtoken`
5. Run blackeye.sh again.

**Comment by j-dogcoder** [comment]
@bobv1st What OS are you running this on??

**Comment by j-dogcoder** [comment]
@bobv1st Did that work??

**Comment by j-dogcoder** [comment]
@bobv1st If this is all good, I will close this.

**Comment by j-dogcoder** [comment]
Please let me know

**Comment by n1c0t1n3** [comment]
Credits: @hamzahmhmmd

I run Kali into a VM and it worked for me.

One way to get that link:

   1. start blackeye.sh file
   2. wait until "Waiting victim open the link..." show up (and shows a blank space)
   3. go to https://dashboard.ngrok.com/status/tunnels to check your generated link

If the first version is to easy for u, and u like to mess up with files and terminal, u got another solution:

credits: @n1c0t1n3 (me)

Delete the NGROK token file and folder. 
`sudo rm -r /home/kali/.ngrok2/` 

Then delete the ngrok file inside blackeye's folder. 

Then go to https://ngrok.com/download and download the updated ngrok file and put it inside blackeye's folder. 

Then just reinsert ur ngrok token
`sudo ./ngrok authtoken _replacewithyourtoken_`


I tried this in Parrot OS (inside a VM) and it worked. But it isn't working in Kali :(. U can still give it a try

**Comment by j-dogcoder** [comment]
Thank you! @bobv1st I am going to close this now. Feal free to reopen it if the issue persists.
