### ISSUE TITLE
Come up with a new name.

### ISSUE THREAD

**Issue by j-dogcoder** [j-dogcoder/Blackeye-2.0#3]
This project needs a better name than blackeye 2.0. Let's brainstorm!

**Comment by imrushikesh** [comment]
Can you tell me what this project is about?

**Comment by j-dogcoder** [comment]
You can read the README.md or look at the original blackeye that can be found [here.](https://github.com/x3rz/blackeye)

**Comment by j-dogcoder** [comment]
@imrushikesh I see you are a web developer. Perhaps you could assist with issue #8.

**Comment by imrushikesh** [comment]
Yeah, Sure Github Page will be the best for now because it is easy to use and manage. 
 I am quite new on Github so I am in the learning phase, but I work on it as soon as possible.

**Comment by j-dogcoder** [comment]
Cool. Thanks!

**Comment by j-dogcoder** [comment]
If you comment on that issue, I can then assign it to you.

**Comment by imrushikesh** [comment]
yeah, no problem.  sure I'll comment on that issue.
