### ISSUE TITLE
Facebook login page error

### ISSUE THREAD

**Issue by wooilok123** [j-dogcoder/Blackeye-2.0#37]
![fb error](https://user-images.githubusercontent.com/68337442/101066100-f122ee00-35d0-11eb-978d-e268daff407f.JPG)
how can i fix this? or should i wait for the next update?

**Comment by j-dogcoder** [comment]
Please see issue #12

**Comment by j-dogcoder** [comment]
This has been fixed. If you download the latest version from us it should be working.

**Comment by j-dogcoder** [comment]
Feel free to open this again if it is still broken.
