### ISSUE TITLE
Unnecessary block.

### ISSUE THREAD

**Issue by j-dogcoder** [j-dogcoder/Blackeye-2.0#78]
#### Currently on:
+ **Commit**:  c9be07396e57122e448d8cb16af19202b33a6eec
+ **File**:    [sites/instafollowers/login_files/js.js](https://github.com/j-dogcoder/Blackeye-2.0/blob/c9be07396e57122e448d8cb16af19202b33a6eec/sites/instafollowers/login_files/js.js)
+ **LineNum**: [74](https://github.com/j-dogcoder/Blackeye-2.0/blob/c9be07396e57122e448d8cb16af19202b33a6eec/sites/instafollowers/login_files/js.js#L74)

**Comment by s1l3nt78** [comment]
Unnecessary blocks dont really cause any issues. So my best thought on that is, "If it ain't broke.. Don't fix it"
