### ISSUE TITLE
Create website

### ISSUE THREAD

**Issue by j-dogcoder** [j-dogcoder/Blackeye-2.0#8]
this can be using GitHub pages or something else, Open to all suggestions.

**Comment by imrushikesh** [comment]
Hey! I would Like to develop a website on GitHub.

**Comment by j-dogcoder** [comment]
There you go! Thanks so much for working on this. I am not sure exactly how I set up the project but I believe you will have to create a branch or fork and then create a pull request when done.

**Comment by imrushikesh** [comment]
yeah, I'll fork then create a branch, when I create a page, I'll pull a request, then You check that out and see if it's good to merge in your project. I just need little info to add on-page about the project, some images, name of people behind the idea, (contributors if you wanna add them on page)

**Comment by j-dogcoder** [comment]
Ok.

**Comment by j-dogcoder** [comment]
@imrushikesh You also may be able to create a branch right off the master in this project.

**Comment by imrushikesh** [comment]
Yeah, That will work fine too.

**Comment by j-dogcoder** [comment]
@imrushikesh It would be cool if we used gitbook [https://gitbook.com/](https://gitbook.com/)

**Comment by imrushikesh** [comment]
yes but its paid, right? use slack its good free

**Comment by j-dogcoder** [comment]
@imrushikesh It is up to you to decide. I was just putting out suggestions.

**Comment by imrushikesh** [comment]
yeah. I check it. hey if you can register here and verify email. that would be a big help  [internshala 1-day Internship](uhttps://internshala.com/1-day-dream-internships?utm_source=eap_copylink&utm_medium=9437956rl)

**Comment by j-dogcoder** [comment]
@imrushikesh Why?

**Comment by s1l3nt78** [comment]
I can make a webpage for this using github pages.
Can check mine at https://s1l3nt78.github.io

**Comment by j-dogcoder** [comment]
Go for it @s1l3nt78!

**Comment by s1l3nt78** [comment]
Okay so the easiest way to do this if im not added to the repo is for you to goto settings tab on the repo.
Go down to the pages section, make sure you set the branch to master and choose a theme and it will make the site.
Then i can start editting the page thats shown otherwise anything i do will be deleted when its pushed to your repo

**Comment by j-dogcoder** [comment]
@s1l3nt78 I added you!

**Comment by s1l3nt78** [comment]
Okay its not giving me the setting option for the repo. 
You youll still need to make the actual start.
But ill send pictures on discord how

**Comment by s1l3nt78** [comment]
SIte is made and will be maintained. No need to leave this open
