### ISSUE TITLE
Detected usage of a possibly undefined superglobal array index: $_SERVER['REMOTE_ADDR']. Use isset() or empty() to check the index exists before using it

### ISSUE THREAD

**Issue by j-dogcoder** [j-dogcoder/Blackeye-2.0#90]
#### Currently on:
+ **Commit**:  c9be07396e57122e448d8cb16af19202b33a6eec
+ **File**:    [sites/messenger/ip.php](https://github.com/j-dogcoder/Blackeye-2.0/blob/c9be07396e57122e448d8cb16af19202b33a6eec/sites/messenger/ip.php)
+ **LineNum**: [13](https://github.com/j-dogcoder/Blackeye-2.0/blob/c9be07396e57122e448d8cb16af19202b33a6eec/sites/messenger/ip.php#L13)

**Comment by s1l3nt78** [comment]
Things like this wont happen during the deployment of the program, as these values are user specified. These are all issues that would not occur at runtime.
