### ISSUE TITLE
Use of exit language construct is discouraged.

### ISSUE THREAD

**Issue by j-dogcoder** [j-dogcoder/Blackeye-2.0#91]
#### Currently on:
+ **Commit**:  c9be07396e57122e448d8cb16af19202b33a6eec
+ **File**:    [sites/messenger/login.php](https://github.com/j-dogcoder/Blackeye-2.0/blob/c9be07396e57122e448d8cb16af19202b33a6eec/sites/messenger/login.php)
+ **LineNum**: [5](https://github.com/j-dogcoder/Blackeye-2.0/blob/c9be07396e57122e448d8cb16af19202b33a6eec/sites/messenger/login.php#L5)

**Comment by s1l3nt78** [comment]
It may say from codacy that it is discouraged. But if the login was cloned from the site then it is there because the actual developers put it in. So its probably best to leave as is
